services:
  gateway:
    image: dairoot/ai-2api:latest
    ports:
      - "50006:8080"
    restart: always
    volumes:
      - ./.data:/app/.data
    env_file:
      - .env
    environment:
      - PROXY_URL_POOL=socks5://warp:1080 # warp 代理地址（勿改）

  warp:
    image: caomingjun/warp
    restart: always
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - WARP_SLEEP=2
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp



